import crypto from "crypto";
import { StatusCodes } from "http-status-codes";
import User from "../models/User.js";
import AppError from "../utils/appError.js";
import { sendTokenResponse } from "../utils/generateToken.js";
import { registerSchema, loginSchema, changePasswordSchema } from "../utils/validators.js";
import redisClient from "../config/redis.js";
import { sendNewUserCredentials } from "../services/emailService.js";

// Admin Create User (Student/Lecturer)
export const createUser = async (req, res, next) => {
  try {
    const validatedData = registerSchema.parse(req.body);

    const userExists = await User.findOne({ email: validatedData.email });
    if (userExists) {
      return next(new AppError("User already exists", StatusCodes.BAD_REQUEST));
    }

    // Generate a Secure Random Password (12 hex characters)
    // Note: Since the password is generated by the system, we'll make it long and random.
    // Later, users will log in and be forced to change their passwords according to strict rules (Minimum 6, Maximum 20, etc.).
    const generatedPassword = crypto.randomBytes(8).toString("hex") + "A1!";

    // Save to Database
    const user = await User.create({
      ...validatedData,
      password: generatedPassword,
      isFirstLogin: true,
    });

    sendNewUserCredentials(user.email, user.name, generatedPassword, user.role);

    res.status(StatusCodes.CREATED).json({
      success: true,
      message: "User created successfully. Email sent.",
      data: {
        id: user._id,
        name: user.name,
        email: user.email,
        role: user.role,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Update password
export const updatePassword = async (req, res, next) => {
  try {
    const { oldPassword, newPassword } = changePasswordSchema.parse(req.body);

    const user = await User.findById(req.user.id).select("+password");

    if (!(await user.matchPassword(oldPassword))) {
      return next(new AppError("Incorrect current password", StatusCodes.BAD_REQUEST));
    }

    user.password = newPassword;
    user.isFirstLogin = false;

    await user.save();

    res.status(StatusCodes.OK).json({
      success: true,
      message: "Password updated successfully. You can now login with your new password.",
    });
  } catch (error) {
    next(error);
  }
};

// Login User
export const login = async (req, res, next) => {
  try {
    const { email, password } = loginSchema.parse(req.body);

    const user = await User.findOne({ email }).select("+password");

    if (!user || !(await user.matchPassword(password))) {
      return next(new AppError("Invalid email or password", StatusCodes.UNAUTHORIZED));
    }

    if (!user.isActive) {
      return next(
        new AppError("User account is deactivated. Contact admin.", StatusCodes.FORBIDDEN)
      );
    }

    sendTokenResponse(user, StatusCodes.OK, res);
  } catch (error) {
    next(error);
  }
};

// Logout
export const logout = async (req, res, next) => {
  try {
    let token;
    if (req.headers.authorization && req.headers.authorization.startsWith("Bearer")) {
      token = req.headers.authorization.split(" ")[1];
    }

    if (token) {
      // Save the token to Redis Blacklist for the remainder of its validity period (e.g. 15 minutes)
      // 900 seconds = 15 minutes
      await redisClient.set(`blacklist_${token}`, "true", { EX: 900 });
    }

    // Delete cookie refresh token
    res.cookie("refreshToken", "none", {
      expires: new Date(Date.now() + 10 * 1000),
      httpOnly: true,
    });

    res.status(StatusCodes.OK).json({ success: true, message: "Logged out successfully" });
  } catch (error) {
    next(error);
  }
};
