export const dummyProjects = [
  {
    id: 1,
    title: 'E-commerce Dashboard',
    description:
      'Modern dashboard design for e-commerce analytics with clean UI components.',
    author: 'Alex Chen',
    date: '2025-05-27',
    category: 'CSC',
    program: 'cs',
    course: 'software-engineering',
    batch: '2024',
    image: 'ecommerce',
  },
  {
    id: 2,
    title: 'Mobile Banking App',
    description:
      'Intuitive mobile banking interface with focus on user experience and security.',
    author: 'Sarah Johnson',
    date: '2025-03-12',
    category: 'BMM',
    program: 'bmm',
    course: 'marketing',
    batch: '2024',
    image: 'banking',
  },
  {
    id: 3,
    title: 'Portfolio Website',
    description:
      'Creative portfolio showcasing photography work with elegant animations.',
    author: 'Mike Rodriguez',
    date: '2025-07-20',
    category: 'GDNM',
    program: 'gdnm',
    course: 'graphic-design',
    batch: '2023',
    image: 'portfolio',
  },
  {
    id: 4,
    title: 'Modern E-Commerce Solution',
    description:
      'Full-stack web application with React and Node.js featuring payment integration and inventory management.',
    author: 'Sarah Johnson',
    date: '2025-05-27',
    category: 'CSC',
    program: 'cs',
    course: 'software-engineering',
    batch: '2024',
    image: 'ecommerce',
  },
  {
    id: 5,
    title: 'Intelligent Customer Support Bot',
    description:
      'AI-powered chatbot using natural language processing to provide automated customer support.',
    author: 'Michael Chen',
    date: '2025-05-27',
    category: 'CSC',
    program: 'cs',
    course: 'computational-biology',
    batch: '2024',
    image: 'ai',
  },
  {
    id: 6,
    title: 'FitTracker Mobile App',
    description:
      'Cross-platform mobile app for fitness tracking with workout plans and progress monitoring.',
    author: 'Emma Davis',
    date: '2025-05-27',
    category: 'CSC',
    program: 'cs',
    course: 'software-engineering',
    batch: '2023',
    image: 'fitness',
  },
  {
    id: 7,
    title: 'Secure Digital Voting Platform',
    description:
      'Blockchain-based voting system ensuring transparency and security in digital elections.',
    author: 'Alex Rodriguez',
    date: '2025-05-27',
    category: 'CSC',
    program: 'cs',
    course: 'software-engineering',
    batch: '2024',
    image: 'blockchain',
  },
  {
    id: 8,
    title: 'Interactive Analytics Dashboard',
    description:
      'Real-time data visualization platform for business intelligence and analytics reporting.',
    author: 'Lisa Wang',
    date: '2025-05-27',
    category: 'CSC',
    program: 'cs',
    course: 'software-engineering',
    batch: '2022',
    image: 'analytics',
  },
  {
    id: 9,
    title: 'Smart Home Automation Hub',
    description:
      'IoT-based home automation system with sensor integration and mobile app control.',
    author: 'David Kim',
    date: '2025-05-27',
    category: 'CSC',
    program: 'cs',
    course: 'software-engineering',
    batch: '2024',
    image: 'iot',
  },
  {
    id: 10,
    title: 'Digital Marketing Campaign Platform',
    description:
      'Comprehensive platform for managing and tracking digital marketing campaigns across multiple channels.',
    author: 'Jessica Martinez',
    date: '2025-04-15',
    category: 'BMM',
    program: 'bmm',
    course: 'marketing',
    batch: '2024',
    image: 'marketing',
  },
  {
    id: 11,
    title: 'Brand Identity Design System',
    description:
      'Complete brand identity package with logo design, color palette, and typography guidelines.',
    author: 'Ryan Thompson',
    date: '2025-06-10',
    category: 'GDNM',
    program: 'gdnm',
    course: 'graphic-design',
    batch: '2023',
    image: 'branding',
  },
  {
    id: 12,
    title: 'Genomic Data Analysis Tool',
    description:
      'Advanced tool for analyzing genomic sequences and identifying patterns in biological data.',
    author: 'Dr. Emily Watson',
    date: '2025-05-20',
    category: 'CSC',
    program: 'cs',
    course: 'computational-biology',
    batch: '2024',
    image: 'genomics',
  },
  {
    id: 13,
    title: 'Social Media Marketing Dashboard',
    description:
      'Analytics dashboard for tracking social media performance and engagement metrics.',
    author: 'Chris Anderson',
    date: '2025-03-25',
    category: 'BMM',
    program: 'bmm',
    course: 'marketing',
    batch: '2023',
    image: 'social',
  },
  {
    id: 14,
    title: 'Protein Structure Prediction',
    description:
      'Machine learning model for predicting protein structures from amino acid sequences.',
    author: 'Dr. James Park',
    date: '2025-07-05',
    category: 'CSC',
    program: 'cs',
    course: 'computational-biology',
    batch: '2024',
    image: 'protein',
  },
  {
    id: 15,
    title: 'E-commerce Marketing Strategy',
    description:
      'Comprehensive marketing strategy document for launching a new e-commerce platform.',
    author: 'Maria Garcia',
    date: '2025-02-18',
    category: 'BMM',
    program: 'bmm',
    course: 'marketing',
    batch: '2022',
    image: 'strategy',
  },
  {
    id: 16,
    title: '3D Animation Showreel',
    description:
      'Showcase of 3D animations and visual effects created using industry-standard software.',
    author: 'Tom Wilson',
    date: '2025-08-12',
    category: 'GDNM',
    program: 'gdnm',
    course: 'graphic-design',
    batch: '2024',
    image: 'animation',
  },
  {
    id: 17,
    title: 'Bioinformatics Sequence Aligner',
    description:
      'Tool for aligning DNA and protein sequences with high accuracy and performance.',
    author: 'Dr. Sarah Lee',
    date: '2025-06-28',
    category: 'CSC',
    program: 'cs',
    course: 'computational-biology',
    batch: '2023',
    image: 'bioinformatics',
  },
  {
    id: 18,
    title: 'Content Marketing Platform',
    description:
      'Platform for creating, scheduling, and analyzing content marketing campaigns.',
    author: 'Kevin Brown',
    date: '2025-05-10',
    category: 'BMM',
    program: 'bmm',
    course: 'marketing',
    batch: '2024',
    image: 'content',
  },
]

export const dummyCategories = [
  {
    id: 1,
    code: 'GDNM',
    name: 'Graphic Design & New Media',
    icon: 'gear',
    count: 1234,
  },
  {
    id: 2,
    code: 'CS',
    name: 'Computer Science',
    icon: 'code',
    count: 892,
  },
  {
    id: 3,
    code: 'IT',
    name: 'Information Technology',
    icon: 'monitor',
    count: 567,
  },
  {
    id: 4,
    code: 'BMM',
    name: 'Business & Management',
    icon: 'chart',
    count: 321,
  },
]

// Program mappings with full names and abbreviations
export const programs = {
  cs: { name: 'Computer Science', abbreviation: 'CS' },
  it: { name: 'Information Technology', abbreviation: 'IT' },
  bmm: { name: 'Business & Management', abbreviation: 'BMM' },
  gdnm: { name: 'Graphic Design & New Media', abbreviation: 'GDNM' },
}

// Course mappings
export const courses = {
  'software-engineering': 'Software Engineering',
  marketing: 'Marketing',
  'computational-biology': 'Computational Biology',
  'graphic-design': 'Graphic Design',
}

